/**
 * Feedback Orchestrator Workflow
 * 
 * Orchestrates multiple agents to provide comprehensive feedback on sales and customer support conversation transcripts.
 * Chains: analyzeTranscript → generateSummary → analyzeDetails
 * 
 * Feedback orchestrator workflow using sequential function calls
 */

import { Env } from "../../types";
import { analyzeTranscript, AnalyzeTranscriptInput } from "../ai/transcriptAnalyzer";
import { generateSummary, GenerateSummaryInput } from "../ai/transcriptSummaryAnalyzer";
import { analyzeDetails, AnalyzeDetailsInput } from "../ai/transcriptDetailAgent";

export interface FeedbackOrchestratorInput {
  transcript: string;
  additionalContext?: any;
  resourceId?: string;
  threadId?: string;
}

export interface FeedbackOrchestratorOutput {
  segmentedAnalysis: string;
  summaryAnalysis: string;
  detailedFeedback: string;
  combinedReport?: string;
}

/**
 * Execute feedback orchestrator workflow
 *  Matches feedbackOrchestratorWorkflow.ts workflow structure
 * Exact code pattern copied with sequential function calls instead of Mastra workflow steps
 */
export async function executeFeedbackOrchestrator(
  input: FeedbackOrchestratorInput,
  env: Env
): Promise<FeedbackOrchestratorOutput> {
  try {
    const { transcript, additionalContext, resourceId, threadId } = input;

    // Store context for downstream steps ( runtimeContext pattern)
    const context = {
      additionalContext,
      resourceId,
      threadId,
    };

    // Step 1: Analyze transcript ( analyzeTranscript step lines 25-72)
    const step1Start = Date.now();
    console.log("Step 1: Analyzing transcript...");
    const analyzeResult = await analyzeTranscript(
      {
        transcript,
        additionalContext,
        resourceId,
        threadId,
      },
      env
    );
    const step1Duration = Date.now() - step1Start;
    console.log(`[Performance] Step 1 completed in ${step1Duration}ms`);

    const { segmentedAnalysis } = analyzeResult;

    // Step 2: Generate summary ( generateSummary step lines 74-116)
    const step2Start = Date.now();
    console.log("Step 2: Generating summary...");
    const summaryResult = await generateSummary(
      {
        transcript,
        segmentedAnalysis,
        additionalContext,
        resourceId,
        threadId,
      },
      env
    );
    const step2Duration = Date.now() - step2Start;
    console.log(`[Performance] Step 2 completed in ${step2Duration}ms`);

    const { summaryAnalysis } = summaryResult;

    // Step 3: Analyze details ( analyzeDetails step lines 118-183)
    const step3Start = Date.now();
    console.log("Step 3: Analyzing details...");
    const detailsResult = await analyzeDetails(
      {
        segmentedAnalysis,
        summaryAnalysis,
        additionalContext,
        resourceId,
        threadId,
      },
      env
    );
    const step3Duration = Date.now() - step3Start;
    console.log(`[Performance] Step 3 completed in ${step3Duration}ms`);

    const { detailedFeedback } = detailsResult;
    
    const totalDuration = Date.now() - step1Start;
    console.log(`[Performance] Total workflow completed in ${totalDuration}ms (Step 1: ${step1Duration}ms, Step 2: ${step2Duration}ms, Step 3: ${step3Duration}ms)`);

    // Step 4: Combine results ( combineResults step lines 185-225)
    const combinedReport = `
# Comprehensive Conversation Feedback Report

## Executive Summary
${summaryAnalysis}

---

## Detailed Psychological & Segmented Analysis
${segmentedAnalysis}

---

## Phrase-Level Communication Feedback
${detailedFeedback}

---

*This comprehensive feedback report was generated by analyzing your sales/customer support conversation through multiple specialized AI agents focused on different aspects of sales and customer service effectiveness.*
    `.trim();

    // Return  pattern exactly (lines 218-223)
    return {
      segmentedAnalysis,
      summaryAnalysis,
      detailedFeedback,
      combinedReport,
    };
  } catch (error) {
    console.error(error);
    throw error;
  }
}

